version: '3.8'

services:
  app:
    build:
      context: ./sistema-culinario
      dockerfile: Dockerfile
    image: receita-docker-compose:1.8
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./sistema-culinario:/var/www
      - ./sistema-culinario/.env:/var/www/.env
    depends_on:
      - db
    networks:
      - laravel_network

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./sistema-culinario:/var/www
      - ./sistema-culinario/docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: senha@123
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: senha@123
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  dbdata: